# Mocha-Lavender

spacing = 2

padding = 1

hide_ascii = true

separator = ""

key_color = "#b4befe"

separator_color = "#9399b2"


[custom_ascii]

path = "~/.config/macchina/ascii"

color = "#b4befe"


[palette]

visible = true

type = "Full"

glyph = "  "


[bar]

visible = false

glyph = ""

symbol_open = '('

symbol_close = ')'


[box]

visible = true

title =

border = "plain"


[box.inner_margin]

x = 1

y = 1
